---
- name: Installing and configuring gitlab
  become: no
  hosts: gitlab
  #become_user:
  # vars:
  #   version: ""
  tasks:
    - name: Create gitadm User group
      group:
        name: gitadm
        state: present
      become: true

    - name: Create /etc/gitlab directory
      file:
        path: /etc/gitlab
        state: directory
        owner: root
        group: gitadm
      become: true

    # - name: Copying configuration file template | gitlab.rb
    #   copy:
    #     src: templates/gitlab.rb.j2
    #     dest: /etc/gitlab/gitlab.rb
    #   become_user: root
    #   become: true

    - name: Copying gitlab secrets file | gitlab-secrets.json
      copy:
        src: files/gitlab-secrets.json
        dest: /etc/gitlab/gitlab-secrets.json
      become_user: root
      become: true

    - name: Downloading gitlab rpm
      shell: curl -JL https://packages.gitlab.com/gitlab/gitlab-ce/packages/el/7/gitlab-ce-9.4.2-ce.0.el7.x86_64.rpm/download -o /tmp/gitlab.rpm

    - name: Installing Gitlab
      yum:
        name: /tmp/gitlab.rpm
        state: present
      become: true

    - name: Configuring gitlab | gitlab-ctl reconfigure
      shell: gitlab-ctl reconfigure
      become: true
      become_user: root
