---
- name: Installing and onfiguring gitlab
  become: no
  hosts: gitlab
  #become_user: 
  # vars:
  #   version: ""
  tasks:
    - name: Create /etc/gitlab directory
      file:
        path: /etc/gitlab
        state: directory
        owner: root
        group: root
      become: true
    
    - name: Copying configuration file template
      template: src=templates/gitlab.rb.j2 dest=/etc/gitlab/gitlab.rb
    
    - name: Copying gitlab secrets file
      file: 
        src: files/gitlab-secrets.json
        dest: /etc/gitlab/gitlab-secrets.json

    - name: Downloading gitlab rpm
      get_url: 
        url: https://packages.gitlab.com/gitlab/gitlab-ce/packages/el/7/gitlab-ce-9.4.2-ce.0.el7.x86_64.rpm/download
        dest: /tmp/gitlab.rpm
        # sha256sum: 

    - name: Installing Gitlab
      yum: 
        name: /tmp/gitlab.rpm
        state: present
      become: true