---
- name: Configuring postgres
  become: yes
  hosts: db
  become_user: postgres
  # vars:
  #   version: ""
  tasks:
   - name: Copy pg_hba.conf 
     template: src=templates/pg_hba.conf.j2 dest=/var/lib/pgsql/data/pg_hba.conf
     notify: Restart postgres
    
   - name: Copy postgres.conf 
     template: src=templates/postgresql.conf.j2 dest=/var/lib/pgsql/data/postgresql.conf
     notify: Restart postgres

   - name: Installing python module psycopg2 required for postgresql_user ansible module - eagle should provide
     yum: name=python-psycopg2 state=present
     become_user: root
   
   - name: Reloading postgres with the new configuration files
     systemd: name=postgresql.service state=reloaded
     become_user: root
   
   - name: Create gitlab user in postgres database
     postgresql_user:
       login_host: "{{ postgres_ip }}"
       login_password: "{{ postgres_password }}"
       port: "{{ postgres_port }}" 
       name: "{{ gitlab_user }}"
       password: "{{ gitlab_user_password }}"

   - name: Creating database for gitlab environment
     postgresql_db:
       login_host: "{{ postgres_ip }}"
       login_password: "{{ postgres_password }}"
       port: "{{ postgres_port }}"       
       name: "{{ gitlab_database }}"
       owner: "{{ gitlab_user }}"
   
   - name: Creating pg_trgm extension on the gitlab database  
     postgresql_ext:  
       name: pg_trgm
       db: "{{ gitlab_database }}"
       login_host: "{{ postgres_ip }}"
       login_user: "{{ postgres_admin_user }}" 
       login_password: "{{ postgres_password }}"
       port: "{{ postgres_port }}"
       state: present
       
  handlers:
    - name: Restart postgres
      systemd: state=restarted enabled=yes name=postgres 
      become: true