---
- name: Installing and configuring gitlab
  become: no
  hosts: gitlab
  #become_user:
  # vars:
  #   version: ""
  tasks:
    - name: Create gitadm User group
      group:
        name: gitadm
        state: present
      become: true

    - name: Create /etc/gitlab directory
      file:
        path: /etc/gitlab
        state: directory
        owner: root
        group: gitadm
      become: true

    - name: Copying configuration file template | gitlab.rb
      template:
        src: templates/gitlab.rb.j2
        dest: /etc/gitlab/gitlab.rb
      become_user: root
      become: true

    - name: Copying gitlab secrets file | gitlab-secrets.json
      copy:
        src: files/gitlab-secrets.json
        dest: /etc/gitlab/gitlab-secrets.json
      become_user: root
      become: true

    - name: Downloading gitlab rpm (by get_url)
      get_url:
        url: https://packages.gitlab.com/gitlab/gitlab-ce/packages/el/7/gitlab-ce-9.4.2-ce.0.el7.x86_64.rpm/download
        dest: /tmp/gitlab.rpm
        use_proxy: true
        validate_certs: False

    - name: Installing Gitlab
      yum:
        name: /tmp/gitlab.rpm
        state: present
      become: true

    - name: Configuring gitlab | gitlab-ctl reconfigure
      shell: gitlab-ctl reconfigure > /tmp/gitlab_reconfigure.log
      become: true
      become_user: root

    - name: Populate the database - this step has to be run only once in production. In vagrant however ...
      expect:
        command: gitlab-rake gitlab:setup
        responses:
          'Do you want to continue \(yes/no\)\?': "yes"
      become_user: root
      become: true
